In [3]:
import numpy as np

In [4]:
data = np.load('monthdata.npz')
totals = data['totals']
counts = data['counts']

In [5]:
#numpy.argmin(a, axis = None, out=None) returns the indicies of the minimum values along an axis
#axis = 0 means column and axis = 1 means row
lowest_precipitation = np.argmin(np.sum(totals, 1))
print('Row with lowest total precipitation:')
print(lowest_precipitation)

Row with lowest total precipitation:
8


In [53]:
average_precipitation = np.divide(np.sum(totals, 0), np.sum(counts, 0)) 
print(average_precipitation)

[27.77978339 30.42629482 29.41007194 17.96654275 21.34456929 20.69498069
 24.97718631 19.85661765 24.06563707 44.68441065 34.61568627 32.36679537]


In [54]:
average_precipitation_city = np.divide(np.sum(totals,1), np.sum(counts, 1))
print("Average precipitation in each city:")
print(average_precipitation_city)


[47.77859779 14.33333333 39.91232877 41.44505495 23.4099723  23.68144044
 17.52197802 36.52222222  6.15426997]


In [6]:
#Review!
#each_quarter = np.reshape(totals, (len(totals) ,4,3))
each_quarter = np.reshape(totals, (len(totals) ,4,3)).sum(axis=2)
print("Quarterly precipitation totals:")
print(each_quarter)

Quarterly precipitation totals:
[[5450 1408 1466 4624]
 [ 189 1339 3148  527]
 [3120 3357 3386 4705]
 [4416 3321 2024 5325]
 [2024 1498 1721 3208]
 [1786 1809 2557 2397]
 [1583 1296 1729 1770]
 [4602 1340 1250 5956]
 [ 338  524  922  450]]
