In [1]:
import numpy as np
import pandas as pd

In [20]:
a = np.array([10,20,30,40], dtype = np.int)

In [21]:
a

array([10, 20, 30, 40])

In [22]:
print( np.arange(6, 14) )
print( np.linspace(0, 5, 11, dtype=np.float32) )
print( np.empty((2, 3), dtype=np.int) ) # uninitialized!
print( np.zeros((2, 3)) )

[ 6  7  8  9 10 11 12 13]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[[24634131        0  1392609]
 [       0  5928040        0]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
some_ints = np.array([[1,2], [3,4]], dtype=np.int64)
ident = np.identity(2, dtype=np.int32)
print(some_ints + ident)
print(some_ints * ident) # element-wise multiplication not matrix
print(some_ints @ ident) # matrix multiplication, or np.dot()
print(some_ints * 3)     # multiplication by a scalar

[[2 2]
 [3 5]]
[[1 0]
 [0 4]]
[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]


In [24]:
def double_plus_single(x):
    return 2*x + 1

double_plus = np.vectorize(double_plus_single,
        otypes=[np.float])
res = double_plus(some_ints)
print(res)
print(res.dtype)

[[3. 5.]
 [7. 9.]]
float64


In [4]:
#Create a dataframe
df = pd.DataFrame(
    {
        'value': [1,2,3,4],
        'word': ['one', 'two', 'three', 'four']
    }
)

In [5]:
df

value   word
0      1    one
1      2    two
2      3  three
3      4   four

In [6]:
df['value']

0    1
1    2
2    3
3    4
Name: value, dtype: int64

In [8]:
df['double'] = df['value']*2

In [9]:
df

value   word  double
0      1    one       2
1      2    two       4
2      3  three       6
3      4   four       8

In [10]:
df[df['value']%2 ==0]

value  word  double
1      2   two       4
3      4  four       8

In [13]:
french_words = pd.Series(
    ['trois', 'deus', 'un'],
    index = [2,1,0]
)

In [14]:
french_words

2    trois
1     deus
0       un
dtype: object

In [17]:
#Add new series to the dataframe
#The indecies will match
df['french_word'] = french_words

In [16]:
df

value   word  double french_word
0      1    one       2          un
1      2    two       4        deus
2      3  three       6       trois
3      4   four       8         NaN

In [26]:
cities = pd.DataFrame(
  [[2463431, 2878.52], [1392609, 5110.21], [5928040, 5905.71]],
  columns=['population', 'area'],
  index=pd.Index(['Vancouver','Calgary','Toronto'], name='city')
)
print(cities)

           population     area
city                          
Vancouver     2463431  2878.52
Calgary       1392609  5110.21
Toronto       5928040  5905.71


In [27]:
cities

population     area
city                          
Vancouver     2463431  2878.52
Calgary       1392609  5110.21
Toronto       5928040  5905.71

In [28]:
def double_plis(x):
    return 2*x+1
double_plus = np.vectorize(double_plus, otypes=[np.float])

cities['density'] = cities['population']/cities['area']
cities['pop-rank'] = cities['population'].rank(ascending = False)
cities['something'] = double_plus(cities['population'])
print(cities)

           population     area      density  pop-rank   something
city                                                             
Vancouver     2463431  2878.52   855.797771       2.0   4926863.0
Calgary       1392609  5110.21   272.515024       3.0   2785219.0
Toronto       5928040  5905.71  1003.781086       1.0  11856081.0


In [29]:
del cities['something']
cities = cities.reset_index()
cities = cities.set_index('pop-rank')
print(cities)

               city  population     area      density
pop-rank                                             
2.0       Vancouver     2463431  2878.52   855.797771
3.0         Calgary     1392609  5110.21   272.515024
1.0         Toronto     5928040  5905.71  1003.781086
